export const GET_INGREDIENTS_REQUEST = "GET_INGREDIENTS_REQUEST";
export const GET_INGREDIENTS_SUCCESS = "GET_INGREDIENTS_SUCCESS";
export const GET_INGREDIENTS_FAILED = "GET_INGREDIENTS_FAILED";

export const ADD_BUN_BURGER = "ADD_BUN_TO_BURGER";
export const ADD_INGREDIENT_BURGER = "ADD_INGREDIENT_BURGER";
export const REMOVE_INGREDIENT_BURGER = "REMOVE_INGREDIENT_BURGER";
export const SORT_INGREDIENTS_BURGER = "SORT_INGREDIENTS_BURGER";
export const REMOVE_ALL_INGREDIENTS_BURGER = "REMOVE_ALL_INGREDIENTS_BURGER";
export const INCREASE_INGREDIENT_COUNTER = "INCREASE_INGREDIENT_COUNTER";
export const DECREASE_INGREDIENT_COUNTER = "DECREASE_INGREDIENT_COUNTER";
export const RESET_COUNTER = "RESET_COUNTER";

export const CREATE_ORDER_REQUEST = "CREATE_ORDER_REQUEST";
export const CREATE_ORDER_SUCCESS = "CREATE_ORDER_SUCCESS";
export const CREATE_ORDER_FAILED = "CREATE_ORDER_FAILED";
export const REMOVE_ORDER = "REMOVE_ORDER";

export const SET_CURRENT_INGREDIENT = "SET_CURRENT_INGREDIENT";
export const REMOVE_CURRENT_INGREDIENT = "REMOVE_CURRENT_INGREDIENT";
