export const GET_INGREDIENTS_REQUEST = "GET_INGREDIENTS_REQUEST";
export const GET_INGREDIENTS_SUCCESS = "GET_INGREDIENTS_SUCCESS";
export const GET_INGREDIENTS_FAILED = "GET_INGREDIENTS_FAILED";

export const ADD_BUN_BURGER = "ADD_BUN_TO_BURGER";
export const ADD_INGREDIENT_BURGER = "ADD_INGREDIENT_BURGER";
export const REMOVE_INGREDIENT_BURGER = "REMOVE_INGREDIENT_BURGER";
