export const GET_INGREDIENTS_REQUEST = "GET_INGREDIENTS_REQUEST";
export const GET_INGREDIENTS_SUCCESS = "GET_INGREDIENTS_SUCCESS";
export const GET_INGREDIENTS_FAILED = "GET_INGREDIENTS_FAILED";
export const ADD_BUN_TO_BURGER = "ADD_BUN_TO_BURGER";
export const ADD_INGREDIENT_TO_BURGER = "ADD_INGREDIENT_TO_BURGER";
export const REMOVE_INGREDIENT_FROM_BURGER = "REMOVE_INGREDIENT_FROM_BURGER";
export const SORT_INGREDIENTS_BURGER = "SORT_INGREDIENTS_BURGER";
export const REMOVE_ALL_INGREDIENTS_FROM_BURGER =
  "REMOVE_ALL_INGREDIENTS_FROM_BURGER";
export const SET_CURRENT_INGREDIENT = "SET_CURRENT_INGREDIENT";
export const REMOVE_CURRENT_INGREDIENT = "REMOVE_CURRENT_INGREDIENT";

export const CREATE_ORDER_REQUEST = "CREATE_ORDER_REQUEST";
export const CREATE_ORDER_SUCCESS = "CREATE_ORDER_SUCCESS";
export const CREATE_ORDER_FAILED = "CREATE_ORDER_FAILED";
export const REMOVE_ORDER = "REMOVE_ORDER";

export const INCREASE_INGREDIENT_COUNTER = "INCREASE_INGREDIENT_COUNTER";
export const DECREASE_INGREDIENT_COUNTER = "DECREASE_INGREDIENT_COUNTER";
export const RESET_COUNTER = "RESET_COUNTER";

export const SIGNUP_USER_REQUEST = "SIGNUP_USER_REQUEST";
export const SIGNUP_USER_FAILED = "SIGNUP_USER_FAILED";

export const LOGIN_USER_REQUEST = "LOGIN_USER_REQUEST";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAILED = "LOGIN_USER_FAILED";

export const LOGOUT_USER_SUCCESS = "LOGOUT_USER_SUCCESS";

export const UPDATE_USER_REQUEST = "UPDATE_USER_REQUEST";
export const UPDATE_USER_FAILED = "UPDATE_USER_FAILED";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
